### ISSUE TITLE
Invalidating/Unloading UI Extensions

### ISSUE THREAD

**Issue by JustasPolis** [ChimeHQ/Extendable#1]
Hey Matt, 

Thanks for amazing libraries and blogs regarding ExtensionKit.

I’m working on a side project that uses UI extensions, and I’m running into an issue with unloading them. Even after the EXHostController is deinitialized, I can still see the extension loaded and consuming memory in the Activity Monitor. I’ve tried invalidating the XPC connection during the deinitialization process, but that hasn’t resolved the issue. Do you have any suggestions on how to properly unload the extensions? I’m using raw ExtensionKit APIs, so this isn’t related to the Extendable library per say. Any help would be appreciated!

**Comment by mattmassicotte** [comment]
Hello!

You know, I've noticed the same thing. I didn't look too deeply into it, because unloading wasn't critical for my application. I just checked, and while I thought I had filed bug it looks like it had I have not. Please do! A number of ExtensionKit-related stuff has been resolved for me in the past.
